name: Allure Report Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test

      - name: Run tests and generate Allure results
        run: |
          npm run test
          npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Prepare Allure Report for GitHub Pages
        if: success()
        run: |
          REPORT_DIR=allure-report-${{ github.sha }}
          mv allure-report $REPORT_DIR
          echo "Report Directory: $REPORT_DIR"

      - name: Deploy Allure Report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./allure-report-${{ github.sha }}
          publish_branch: gh-pages
          cname: allure-report
          keep_files: true

      - name: Display Allure Report URL
        run: |
          echo "Allure Report URL: https://manjunathnp.github.io/Playwright-AutomationFramework-POM/allure-report-${{ github.sha }}/index.html"

      - name: Debug - List Files in gh-pages Branch
        if: always()
        run: |
          git clone --single-branch --branch gh-pages https://github.com/manjunathnp/Playwright-AutomationFramework-POM.git gh-pages
          ls -R gh-pages